resolver: lts-7.24
packages:
- '.'
extra-deps:
# Using newest aeson, with no contents in tagged
# unions with nullary constructors
- aeson-1.2.1.0
- github: mumuki/language-javascript
  commit: 63f9a9cb7445cc10aa0ab6966b66caf58e59f9d3
- github: julian-berbel/language-python
  commit: cbdf9b33cc3c30e66c8455165ed1c7d70a300a3e
flags: {}
extra-package-dbs: []
